sonar.projectKey=rBiblia_rbiblia-web
sonar.organization=rbiblia
sonar.projectName=rbiblia-web

sonar.coverage.exclusions=
sonar.exclusions=**/bin/console.php,**/public_html/**,**/src/vendor/**,**/src/view/**,**/src/language/**,**/src/config/**,**/.github/**,**/tests/**,**/rector.php,**/*.json,**/Dockerfile,**/webpack.config.js,**/assets/css/**,**/assets/scss/**

sonar.php.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info
