sonar.projectKey=rBiblia_rbiblia-web
sonar.organization=rbiblia
sonar.projectName=rbiblia-web

sonar.coverage.exclusions=**/assets/**
sonar.exclusions=**/bin/console.php,**/public_html/**,**/src/vendor/**,**/src/view/**,**/src/language/**,**/src/config/**,**/.github/**,**/tests/**,**/rector.php,**/*.json,**/Dockerfile,**/webpack.config.js

sonar.php.coverage.reportPaths=coverage.xml
