<!DOCTYPE html>
<html>
    <head>
        <title>rBiblia Web</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="noindex, follow">
        <meta name="author" content="Rafał Toborek">
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <link href="/assets/app.css" rel="stylesheet">
    </head>
    <body>
        Hello world!

        <script src="/assets/app.js"></script>
    </body>
</html>
