<!DOCTYPE html>
<html>
    <head>
        <title>rBiblia Web</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="noindex, follow">
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <link href="/assets/app.css" rel="stylesheet">
    </head>
    <body>
        <div id="root"></div>
        <script src="/assets/app.js"></script>
        <?= (isset($matomo) ? $matomo : '<!-- the Matomo code will be placed here only in prod env -->').PHP_EOL ?>
    </body>
</html>
